### ISSUE TITLE
Column Style and number type sorting not working

### ISSUE THREAD

**Issue by McAnix** [briangann/grafana-datatable-panel#108]
I cannot reference specific Column Styles using the name or regex which means I cannot set the type (hidden, number, etc.). 

Sorting is mostly fixed however it's lexicographical, even on "number" columns, all 1's then 2's etc.. I suspect if the above reference issue is fixed then numeric sorting will be fixed too. 

It seems that Grafana 7.0 broke a few things for the datatable-panel. 

Plugin version: 1.0.2
Grafana-server: 7.0.4 
Data source: MariaDB 10.2

**Comment by bneelon85** [comment]
I am having the same issue in Grafana Cloud. I believe it's assuming a type of 'string' as the sorting is alphabetical not numeric. You can see in the screenshot compared with the base table visualization where I have both tables sorted descending on `On Order`. If I edit the regex in Column Style to assign a numeric type, the table disappears from the panel.

Plugin version: 1.0.2
Grafana-server: Grafana Cloud (most recent version as of 2020-07-14)
Data source: SQL Server (not sure of the version--hosted by a third party SaaS company on Azure)

![image](https://user-images.githubusercontent.com/12244629/87386564-616b9d00-c566-11ea-89b1-b4902be3f4b3.png)

**Comment by AntonSemenovKazan** [comment]
Same issue for me on 1.0.2
http://skrinshoter.ru/s/280820/BP91ID

**Comment by HenningRath** [comment]
Hi,

this might be caused by using new Regex() instead of Utils.StringToJsRegex() in transformers.ts
<pre>
@@ -2,6 +2,7 @@ import _ from 'lodash';
 import flatten from 'grafana/app/core/utils/flatten';
 import TimeSeries from 'grafana/app/core/time_series2';
 import TableModel from 'grafana/app/core/table_model';
+import { StringToJsRegex } from './Utils';

 const transformers: any = {};

@@ -173,7 +174,7 @@ transformers.table = {
       let c = model.columns[i];
       for (let j = 0; j < panel.styles.length; j++) {
         let s = panel.styles[j];
-        if (s.pattern && new RegExp(s.pattern).test(c.text)) {
+        if (s.pattern && StringToJsRegex(s.pattern).test(c.text)) {
           // if matched column Type is number, then set the num for datatables internal column type
           c.type = s.type === 'number' ? 'num' : c.type;
           break;
</pre>
changing the code lets me use feature "Right Align Numbers" on columns with regex pattern correct. Otherwise columns defined by regex have type=undefinded instead of type=num;
