### ISSUE TITLE
Panel size and contents w/ scroll overflow panel view

### ISSUE THREAD

**Issue by dacto** [briangann/grafana-datatable-panel#42]
A panel with the scroll (instead of paging) option enabled ends up overflowing the panel view.

Resizing the panel larger to show bottom bounds (to include the bottom scrollbar arrow, table, and "Showing # to # entries of # entries") is only a temporary/momentary solution. Upon refresh the content in the panel again overflows the, now larger, view.

An image showing an example of the problem:
  * **Left**: after resizing and saving the dashboard with the new panel size.
  * **Right**: after refeshing the page.

![size-scrollbar-bug](https://user-images.githubusercontent.com/1351348/48277533-cf5dd980-e3ff-11e8-8859-beb029d315b3.png)

**Comment by pcsegal** [comment]
This seems related to a behavior that I'm seeing in Grafana 7. However, in my case, it's unrelated to whether scroll mode is enabled or not.

What I'm seeing is that the table contents can become bigger than the panel bounds. In previous Grafana versions, the overflowed content got hidden past the panel bounds (that is, only the portion within the panel bounds was shown). However, in Grafana 7, the behavior is different: the overflown content is visible.

For example, this happens when the cells each row have enough text in them that the text wraps to a new line and the rows increases in height as a result. When that happens, the height of the table becomes bigger than the panel bounds, and the DataTable overflows past the bottom of the panel.
