### ISSUE TITLE
For type String there is no threshold option to colors

### ISSUE THREAD

**Issue by matheusnicolas** [briangann/grafana-datatable-panel#79]
I am in version 6.+ of Grafana and I missed the option of threshold colors for string, because besides classifying the types (ex: 0 - normal, 1 - critical) I would like to use the range with the colors as in the new version of Table of Grafana. Any plans to update this in the plugin, which by the way is very good?

Update: I tried this way after, but doesn't work
![test](https://user-images.githubusercontent.com/20845065/72931276-51ec6380-3d3c-11ea-82d2-de243b29aba8.png)

**Comment by briangann** [comment]
this is next :)

**Comment by orena1** [comment]
I also have it.. 
![image](https://user-images.githubusercontent.com/8983713/88627784-8ce99e00-d0b5-11ea-9978-536d7698ef86.png)

**Comment by briangann** [comment]
> I also have it..
the latest version should handle thresholds for "Number" type, if you refresh the panel does it reflect the colors expected or does it always show the default (white)

**Comment by orena1** [comment]
Thanks @briangann , I've refreshed it but it still does not work.

Maybe because some of the values are text?
![image](https://user-images.githubusercontent.com/8983713/89038237-a22a2b00-d348-11ea-9a17-c1ac264eb121.png)

It does work perfectly with the normal table plugin :
![image](https://user-images.githubusercontent.com/8983713/89038355-dbfb3180-d348-11ea-852b-295020b70bee.png)

I'm using 1.0.2v
